name: MLSPP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_OUTPUT_ON_FAILURE: 1
  VCPKG_BINARY_SOURCES: files,${{ github.workspace }}/vcpkg_cache,readwrite
  CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  build-and-unit-test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        crypto: [openssl_1.1]

    env:
      BUILD_DIR: "${RUNNER_TEMP}/build_${{ matrix.crypto }}"
      CRYPTO_DIR: "./alternatives/${{ matrix.crypto }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: ./.github/actions/prepare-build
      with:
        os: ${{ matrix.os }}
        crypto: ${{ matrix.crypto }}
        cache-dir: ${{ github.workspace }}/vcpkg_cache

    - name: Build
      run: |
        # XXX(RLB): If we do not have SANITIZERS=ON here, the Windows CI builds
        # hang in the middle of unit testing.
        cmake -B "${{ env.BUILD_DIR }}" -DVCPKG_MANIFEST_DIR="${{ env.CRYPTO_DIR }}" -DTESTING=ON -DSANITIZERS=ON
        cmake --build "${{ env.BUILD_DIR }}"

    - name: Unit Test (non-Windows)
      if: matrix.os != 'windows-latest'
      run: |
        cmake --build "${{ env.BUILD_DIR }}" --target test

    - name: Unit Test (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cmake --build "${{ env.BUILD_DIR }}" --target RUN_TESTS
