name: Doctest fail test case 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_OUTPUT_ON_FAILURE: 1
  VCPKG_BINARY_SOURCES: files,${{ github.workspace }}/vcpkg_cache,readwrite
  CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

jobs:
  build-and-unit-test:
    name: Build and test
    runs-on: windows-latest

    env:
      BUILD_DIR: "${RUNNER_TEMP}/build"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Build
      run: |
        cmake -B "${{ env.BUILD_DIR }}"
        cmake --build "${{ env.BUILD_DIR }}"
    
    - name: Unit Test (Windows)
      run: |
        cmake --build "${{ env.BUILD_DIR }}" --target RUN_TESTS
